apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- "secondeimage.yaml" 

patches:
- path: monpatch.json
  target:
    kind: Deployment
    name: labgo

configMapGenerator:
- name: applicative-config
  options:
    disableNameSuffixHash: true
  files:
  - configuration.yaml

secretGenerator:
- literals:
  - db-password=12345
  name: sl-demo-app
  type: Opaque

configurations:
- kustomizeconfig.yaml