apiVersion: v1
kind: Namespace
metadata:
  name: logtosiem
status:
  phase: Active
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logtosiem
  namespace: logtosiem
  
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: crblogtosiem
subjects:
- kind: ServiceAccount
  name: logtosiem
  namespace: logtosiem
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io