apiVersion: v1
kind: Namespace
metadata:
  name: labgo
status:
  phase: Active
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: labgo
  namespace: labgo
  
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: crblabgo
subjects:
- kind: ServiceAccount
  name: labgo
  namespace: labgo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io